# Generated by Django 3.0.9 on 2020-08-04 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('gradeid', models.AutoField(primary_key=True, serialize=False, verbose_name='班级编号')),
                ('grade_name', models.CharField(max_length=20, unique=True, verbose_name='班级名称')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
                'db_table': 'grade',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('sex', models.BooleanField(default=True, verbose_name='性别')),
                ('memo', models.CharField(default=None, max_length=255, verbose_name='备注')),
                ('teacherid', models.AutoField(primary_key=True, serialize=False, verbose_name='老师编号')),
            ],
            options={
                'verbose_name': '老师',
                'verbose_name_plural': '老师',
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='TeachersGrade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('grade', models.ForeignKey(db_column='gradeid', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Grade')),
                ('teacher', models.ForeignKey(db_column='teacherid', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Teachers')),
            ],
            options={
                'verbose_name': '老师班级',
                'verbose_name_plural': '老师班级',
                'db_table': 'teacher_grade',
            },
        ),
        migrations.AddField(
            model_name='teachers',
            name='grades',
            field=models.ManyToManyField(default=None, through='app.TeachersGrade', to='app.Grade'),
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('sex', models.BooleanField(default=True, verbose_name='性别')),
                ('memo', models.CharField(default=None, max_length=255, verbose_name='备注')),
                ('cls', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Grade')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'db_table': 'students',
            },
        ),
    ]
